### ISSUE TITLE
Intermittent SSL error 

### ISSUE THREAD

**Issue by AnnaAAL** [cloudfoundry/buildpacks-github-config#19]
We've observed an intermittent SSL error while this [curl](https://github.com/cloudfoundry/buildpacks-github-config/blob/main/buildpack/scripts/install_go.sh#L28) was executed with both nodejs-buildpack and staticfile-buildpack. 
It seems there's no retry for this type error (connection reset by peer): 

<img width="2022" alt="SSL_error" src="https://user-images.githubusercontent.com/97691430/219688100-e4c0f3b8-b61e-416f-98a8-aa057b8c6949.png">

It seems that this issue doesn't occur very often, but we've experienced it twice already. 

Could you advise on a mechanism to overcome it in all cases?

**Comment by robdimsdale** [comment]
Hi @AnnaAAL we haven't really encountered this. A quick search for `openssl errno 104` suggests a generic client-side closure.

We could add a couple of flags to `curl` to potentially give me information (e.g. `--fail-with-error`). That might shed some more light on the issue.

If this continues to happen, let us know and we can add those flags. Or you are welcome to submit a PR
