### ISSUE TITLE
Upgrade CF CLI to v7

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/buildpacks-github-config#3]
Upgrade CF CLI to v7 now that CF CLI v6 is deprecated.

**Comment by johnnyr0x** [comment]
Duplicate of https://github.com/orgs/cloudfoundry/projects/37/views/1?pane=issue&itemId=17705415. Can close

**Comment by robdimsdale** [comment]
FYI @johnnyr0x I didn't view them as duplicate issues because we would need to do the work in both this repo and in the `buildpacks-ci` repo. So I filed issues in both places it would need to be implemented.

But, given we closed the other one as low-priority technical debt, I think it's fine to keep this one closed too.
